"""
MNE Porting Verification Script
Generates test data for validating C++ implementation against Python MNE.

Usage:
    python gen_test_data.py
"""

import numpy as np
import scipy.signal
import os

OUTPUT_DIR = "data"

def ensure_dir(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

def generate_signal(n_samples=1000, sfreq=1000):
    """Generate a composite signal with known frequencies."""
    t = np.arange(n_samples) / sfreq
    # Signal: 10Hz + 20Hz + 50Hz noise
    sig = (np.sin(2 * np.pi * 10 * t) + 
           0.5 * np.sin(2 * np.pi * 20 * t) + 
           0.2 * np.random.randn(n_samples))
    return t, sig

def save_data(name, data):
    """Save numpy array to text file compatible with IOUtils::read_eigen_matrix."""
    filepath = os.path.join(OUTPUT_DIR, f"{name}.txt")
    # Save as space-separated values
    # Add header with dimensions
    header = f"Dimensions (rows x cols): {data.shape[0] if data.ndim > 1 else data.size} x {data.shape[1] if data.ndim > 1 else 1}\nDescription: Generated by gen_test_data.py"
    np.savetxt(filepath, data, header=header)
    print(f"Saved {name} to {filepath}")

def main():
    ensure_dir(OUTPUT_DIR)
    
    # 1. Basic Signal
    sfreq = 1000
    n_samples = 1000
    t, sig = generate_signal(n_samples, sfreq)
    
    save_data("signal_raw", sig)
    
    # 2. Hilbert Transform (Envelope)
    # Using scipy.signal.hilbert
    sig_analytic = scipy.signal.hilbert(sig)
    amplitude_envelope = np.abs(sig_analytic)
    save_data("signal_hilbert_abs", amplitude_envelope)
    
    # 3. Convolution (Simple Moving Average)
    # Window size 50 samples
    window = np.ones(50) / 50.0
    sig_conv = np.convolve(sig, window, mode='same')
    save_data("signal_conv_ma50", sig_conv)
    
    # 4. Window Functions
    n_win = 512
    # Hanning
    win_hanning = np.hanning(n_win)
    save_data("window_hanning_512", win_hanning)
    
    # Hamming
    win_hamming = np.hamming(n_win)
    save_data("window_hamming_512", win_hamming)
    
    # Blackman
    win_blackman = np.blackman(n_win)
    save_data("window_blackman_512", win_blackman)
    
    print("Verification data generation complete.")

if __name__ == "__main__":
    main()
