#ifndef PREPROCESSING_GLOBAL_H
#define PREPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATICBUILD)
#  define PREPROCESSINGSHARED_EXPORT
#elif defined(MNE_PREPROCESSING_LIBRARY)
#  define PREPROCESSINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PREPROCESSINGSHARED_EXPORT Q_DECL_IMPORT
#endif

namespace PREPROCESSINGLIB {
}

#endif // PREPROCESSING_GLOBAL_H
